version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_local
    ports:
      - "6333:6333"  # REST API and Web UI
      - "6334:6334"  # GRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped 